name: ci
on:
  push:
    branches: [ main, master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: PRO
    steps:
      # - name: Docker login
      #   run: docker login --username=$DOCKER_USER --password=$DOCKER_PASS
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: build
        run: |
          docker build -t nikodonoso86/base-image:latest .
          docker build -t nikodonoso86/base-image:$GITHUB_JOB .
      - name: push
        run: |
          docker login --username=$DOCKER_USER --password=$DOCKER_PASS
          docker push nikodonoso86/base-image:latest
          docker push nikodonoso86/base-image:$GITHUB_JOB