name: ci
on:
  push:
    branches: [ main, master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: PRO
    steps:
      - name: Docker login
        run: docker login --password=${{ secrets.DOCKER_PASS }} --username=${{ secrets.DOCKER_USER }}
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: build
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/base-image:latest .
          docker build -t ${{ secrets.DOCKER_USER }}/base-image:$GITHUB_JOB .
      - name: push
        run: |
          # docker login -u $DOCKER_USER -p "$DOCKER_PASS"
          docker push ${{ secrets.DOCKER_USER }}/base-image:latest
          docker push ${{ secrets.DOCKER_USER }}/base-image:$GITHUB_JOB