name: ci
on:
  push:
    paths:
      - dir1/dir2/*/Dockerfile

permissions: write-all
jobs:
  prep-matrix:
    name: Get changed Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: space-delimited
          token: ${{ secrets.GH_TOKEN }}
      - run: |
          for image in ${{ steps.files.outputs.all }}
          do 
            if [[ $image =~ "Dockerfile" ]]
              then echo building $image
            fi
          done