name: ci
on:
  push:
    branches: 
      - main
      - master
      - tf-update
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: PRO
    steps:
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: build
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/base-image:latest .
          docker build -t ${{ secrets.DOCKER_USER }}/base-image:$GITHUB_RUN_ID .
      - name: push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/base-image:$GITHUB_RUN_ID
      - name: latest
        if: ${{ github.ref == 'master' }}
        run: |
          docker push ${{ secrets.DOCKER_USER }}/base-image:latest