name: ci
on:
  push:

permissions: write-all
jobs:
  prep-matrix:
    name: Get cahnged Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: space-delimited
          token: ${{ secrets.GH_TOKEN }}
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done